parameters:
- name: 'PoolImage'
  default: 'windows-2019'
  type: string
- name: 'BuildJobDisplayName'
  default: 'Build Job'
  type: string

trigger: none


jobs:
- job: Build
  displayName: '${{parameters.BuildJobDisplayName}}'
  pool:
    vmImage: ${{parameters.PoolImage}}

  steps:
  - checkout: self
  
  - task: PowerShell@2
    displayName: 'Add variables to Variable group'
    inputs:
      filePath: '$(build.SourcesDirectory)/proserv-cdm-demo-variables/Scripts/AddVariables.ps1'
      arguments: '$(build.SourcesDirectory)/proserv-cdm-demo-variables'
